name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SERVER_HOST
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/perso/wyze-academy_ecommerce/

            # Pull latest changes and store changed files
            CHANGED_FILES=$(git pull origin master | grep -E 'frontend/|backend/')

            if echo "$CHANGED_FILES" | grep -q "backend/"; then
              echo "Backend changed, rebuilding backend..."
              cd ~/perso/wyze-academy_ecommerce/backend
              sudo docker stop wyze-ecommerce || true
              sudo docker rm wyze-ecommerce || true
              sudo docker build -t wyze-ecommerce .
              sudo docker run -d --name wyze-ecommerce -p 2005:3005 wyze-ecommerce
            else
              echo "No backend changes."
            fi

            if echo "$CHANGED_FILES" | grep -q "frontend/"; then
              echo "Frontend changed, rebuilding frontend..."
              cd ~/perso/wyze-academy_ecommerce/frontend
              sudo docker stop wyze-frontend || true
              sudo docker rm wyze-frontend || true
              sudo docker build -t wyze-frontend .
              sudo docker run -d --name wyze-frontend -p 2006:3000 wyze-frontend
            else
              echo "No frontend changes."
            fi

            exit 0
